# Generated by Django 2.2.7 on 2020-02-22 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('email', models.EmailField(default='none', max_length=30)),
                ('ph', models.CharField(default='none', max_length=10)),
                ('address', models.CharField(default='none', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='none', max_length=30)),
                ('age', models.IntegerField(default='0')),
                ('breed', models.CharField(default='none', max_length=30)),
                ('pet_type', models.CharField(choices=[('dog', 'dog'), ('cat', 'cat'), ('bird', 'bird')], default='none', max_length=5)),
                ('owner', models.ForeignKey(default='none', on_delete=django.db.models.deletion.CASCADE, to='apis.owner')),
            ],
        ),
    ]
