# Generated by Django 2.2.7 on 2020-02-23 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='sex',
            field=models.CharField(default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default='-100', on_delete=django.db.models.deletion.CASCADE, to='apis.owner'),
        ),
    ]
